version: '2'
volumes:
  var_hyperledger_production:
  ccenv_devmode0_gopath:
  unittest_node_modules:
  unittest_tmp:
services:
  # Note: The defaults in compose-defaults.yml assume that the service extending default_membersrvc is called membersrvc.
  membersrvc:
    extends:
      file: compose-defaults.yml
      service: default_membersrvc

  # Note: The defaults in compose-defaults.yml assume that the service extending default_membersrvc is called membersrvc.
  vp0:
    extends:
      file: compose-defaults.yml
      service: default_vp_deploy_mode_dev
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    depends_on:
      - membersrvc

  # There is no chaincode corresponding to registrar.js

  unittest:
    extends:
      file: compose-defaults.yml
      service: default_unittest
    environment:
      # If SDK_DEPLOY_MODE is "dev", then it is assumed that we will build and run the chaincode ourselves (ccenv_devmode0).
      - SDK_DEPLOY_MODE=dev
      - SDK_PEER_ADDRESS=vp0:7051
      - SDK_EVENTHUB_ADDRESS=vp0:7053

    # $$GOPATH (double dollar) is required to prevent docker-compose doing its own substitution before the
    # value gets to the container.
    command: |
      bash -x -c "
        npm install && \
        node test/unit/registrar.js
      "
    depends_on:
      - membersrvc
      - vp0
